services:
  planetarium:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8015:8010"
    volumes:
      - ./:/app
      - my_media:/files/media
    command: >
      sh -c "
      python manage.py wait_for_db
      && python manage.py migrate
      && python manage.py runserver 8010"
    depends_on:
      - db

  db:
    image: postgres:15.7-alpine3.20
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - my_db:$PG_DATA

volumes:
  my_db:
  my_media:
