# Generated by Django 5.0.6 on 2024-06-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speaker',
            new_name='ShowSpeaker',
        ),
    ]
